---
title: "Tehtävän tulokset"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Tulokset

```{r tulokset, echo=FALSE, message=FALSE}
library(gsheet)
library(ggplot2)
library(tidyverse)
library(cowplot)
library(patchwork)

u <- "" # add url for google sheet here (check sharing settings if it doesn't work)

vastaukset <- read.csv(text=gsheet2text(u, format='csv'), stringsAsFactors=FALSE, 
         skip=1, header = FALSE, 
         col.names = c("timestamp", "metsa", "keskiarvo", "keskihajonta"))


df_list <-list ()
for(i in 1:nrow(vastaukset)) {
  df_list[[i]] <- data.frame(id = rep(i, 60),
                             metsa = rep(vastaukset$metsa[i], 60),
                             dbh = 1:60,
                             density = dnorm(1:60, 
                                             vastaukset$keskiarvo[i],
                                             vastaukset$keskihajonta[i]))
}

final_densities <- do.call(rbind, df_list)

final_densities %>%
  ggplot(aes(dbh, density, col=factor(id))) +
  geom_line() + 
  facet_wrap(metsa ~ ., ncol=1) +
  theme(legend.position = "none") +
  xlab("Rungon läpimitta (cm)") 

```


```{r, echo=FALSE, message=FALSE}
url1 <- "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Young_trees_in_Inverawe_Forest_-_geograph.org.uk_-_1839009.jpg/640px-Young_trees_in_Inverawe_Forest_-_geograph.org.uk_-_1839009.jpg"

url2 <- "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Meenikunno_maastikukaiteala.jpg/640px-Meenikunno_maastikukaiteala.jpg"

url3 <- "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/D%C3%BClmen%2C_Rorup%2C_NSG_Roruper_Holz_--_2021_--_8187-91.jpg/640px-D%C3%BClmen%2C_Rorup%2C_NSG_Roruper_Holz_--_2021_--_8187-91.jpg"

p1 <- ggdraw() + draw_image(url1, scale = 1)
p2 <- ggdraw() + draw_image(url2, scale = 1)
p3 <- ggdraw() + draw_image(url3, scale = 1)

# plot_grid(p1, p2, p3)
p1 + p2 + p3
```